server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liulei-dot/springcloud-config.git
          # 访问http://config-3344.com:3344/main/config-dev.yml
  rabbitmq:
    host: 172.21.14.196
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"  #要开启所有监控